const { withGradleProperties } = require('expo/config-plugins');

/**
 * Keep release shrinking in source control: android/ is generated by Expo.
 * Retain Expo's default ProGuard rules, Hermes packaging and supported ABIs.
 */
module.exports = function withAndroidReleaseOptimizations(config) {
  return withGradleProperties(config, (modConfig) => {
    const releaseProperties = {
      'android.enableMinifyInReleaseBuilds': 'false',
      'android.enableShrinkResourcesInReleaseBuilds': 'false',
      'android.enableAbiSplits': 'true',
    };

    for (const [key, value] of Object.entries(releaseProperties)) {
      modConfig.modResults = modConfig.modResults.filter(
        (item) => item.type !== 'property' || item.key !== key,
      );
      modConfig.modResults.push({ type: 'property', key, value });
    }

    return modConfig;
  });
};
